from __future__ import annotations

import json
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..lifespan import AppState

# Injected before </head> when the UI is mounted at a non-root ASGI prefix.
# Patches window.fetch and history.push/replaceState so that root-relative
# URLs generated by the CDN-served SPA are rebased to the actual mount path.
# {b} is replaced at serve-time with the JSON-encoded root_path string.
_REBASE_SCRIPT = """\
<script>
!function(){{if(!window.__aiUiRebased){{window.__aiUiRebased=1;
var b={b};
var f=window.fetch;
window.fetch=function(u,o){{
  if(typeof u==='string'&&u.charAt(0)==='/'&&u.indexOf(b)!==0)u=b+u;
  return f.call(this,u,o);
}};
var p=history.pushState.bind(history);
history.pushState=function(s,t,u){{
  if(u&&typeof u==='string'&&u.charAt(0)==='/'&&u.indexOf(b)!==0)u=b+u;
  return p(s,t,u);
}};
var r=history.replaceState.bind(history);
history.replaceState=function(s,t,u){{
  if(u&&typeof u==='string'&&u.charAt(0)==='/'&&u.indexOf(b)!==0)u=b+u;
  return r(s,t,u);
}};
}}}}();
</script>
</head>"""


class _DynamicUIApp:
    """ASGI wrapper that lazily creates the Pydantic AI web UI,
    recreates it when the agent is replaced on reload, and injects a
    fetch/history rebase shim when mounted under a non-root path prefix."""

    def __init__(self, app_state: AppState) -> None:
        self._state = app_state
        self._last_agent: Any = None
        self._web_app: Any = None

    async def __call__(self, scope: Any, receive: Any, send: Any) -> None:
        agent = self._state.agent
        if agent is not self._last_agent:
            self._last_agent = agent
            self._web_app = agent.to_web()

        root_path: str = (
            scope.get('root_path', '').rstrip('/') if scope['type'] == 'http' else ''
        )

        if not root_path:
            await self._web_app(scope, receive, send)
            return

        # Intercept HTML responses to inject the rebase script.
        start_msg: dict[str, Any] = {}
        body_parts: list[bytes] = []
        is_html = False

        async def intercept(message: dict[str, Any]) -> None:
            nonlocal is_html

            if message['type'] == 'http.response.start':
                start_msg.update(message)
                ct = dict(message.get('headers', [])).get(b'content-type', b'')
                is_html = b'text/html' in ct
                if not is_html:
                    await send(message)

            elif message['type'] == 'http.response.body':
                if not is_html:
                    await send(message)
                    return
                body_parts.append(message.get('body', b''))
                if not message.get('more_body', False):
                    body = b''.join(body_parts)
                    injection = _REBASE_SCRIPT.format(
                        b=json.dumps(root_path)
                    ).encode()
                    body = body.replace(b'</head>', injection, 1)
                    new_headers = [
                        (k, v) for k, v in start_msg.get('headers', [])
                        if k.lower() != b'content-length'
                    ]
                    new_headers.append(
                        (b'content-length', str(len(body)).encode())
                    )
                    await send({**start_msg, 'headers': new_headers})
                    await send({
                        'type': 'http.response.body',
                        'body': body,
                        'more_body': False,
                    })

            else:
                await send(message)

        await self._web_app(scope, receive, intercept)


def build_ui_app(app_state: AppState) -> _DynamicUIApp:
    return _DynamicUIApp(app_state)
